# Generated by Django 4.2.5 on 2023-09-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='name',
            field=models.CharField(default='unkown', max_length=256),
        ),
    ]
