# Generated by Django 4.2.5 on 2023-09-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_volume_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='filament',
            name='prix',
            field=models.TextField(default='#'),
        ),
    ]
