# Generated by Django 4.2.5 on 2023-09-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_filament_prix'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknown', max_length=256)),
                ('volume', models.IntegerField(default='0')),
                ('description', models.TextField(default='unknown')),
                ('filament', models.CharField(default='unknow', max_length=256)),
                ('prix', models.TextField(default='#')),
            ],
        ),
        migrations.DeleteModel(
            name='Filament',
        ),
        migrations.DeleteModel(
            name='Volume',
        ),
    ]
